# Database settings
database:
  # Currently supported: 'postgres'
  type: postgres

  # (For Postgres)
  hostname: localhost
  port: 5432
  username: copperbottom
  password: copperbottom
  database: copperbottom

# UMAP server settings
server:
  # port: 14369
  # (uncomment to change to a non-standard port)

  # If set, the fully formed target URL to redirect to if an HTTP request is
  # made to the UMAP port.
  redirect_uri: http://localhost:14370/

  # Admin credentials for managing the server.
  admin:
    username: admin
    password: admin123

# HTTP (WebSocket) server settings
http:
  # The port that the HTTP websocket interface should be started on.
  port: 14370

  # The list of origins allowed to connect to the WebSocket server.
  allowedOrigins:
    - ""
