name: copperbottom
description: The open-source UMAP implementation.
version: 0.0.1
homepage: https://samjakob.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  postgres: ^2.4.3
  pubspec_extract: ^2.0.4
  messagepack: ^0.2.1
  logger: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
